[project]
name = "workspace"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "onnxocr>=2025.5",
]

[dependency-groups]
dev = [
    "lefthook>=2.0.4",
    "pyright>=1.1.405",
    "ruff>=0.13.2",
]

[tool.ruff]
# https://docs.astral.sh/ruff/
src = ["src"]
line-length = 120 # デフォルトの88では短いので緩くする

[tool.ruff.lint]
# https://docs.astral.sh/ruff/linter/
select = ["ALL"] # 無効にしない限り全てのルールを適用する
ignore = [
    "FIX", # TODOコメント等を使用可能にする
    "COM812", "ISC001", # Ruffの警告が出るので無視
    "TD001", # FIXME等をコメントのタグに使用可能にする
    "TD002", # TODOのauthorを不要にする
    "TD003", # TODOのチケットへのリンクを不要にする
    "ANN201", "ANN202", "ANN204", "ANN205", "ANN206", # 関数やメソッドの返り値の型を推論に任せた方が楽な場合が多いので無視する
    "D400", "D415", # 日本語に合わないdocstring末尾のルールを無視
]
extend-select = [
    "I", # isort
]

[tool.ruff.lint.per-file-ignores]
"tests/**/*.py" = [
    "S101", # assertを使用可能にする
    "PLR2004", # マジックナンバーの使用を可能にする
    "D", # ドキュメントを不要にする
    "N802", # 日本語を使用するため、lowercaseでなくても良いようにする
    "PLC2401", # 日本語を使用するため、ASCII文字列以外を使用可能にする
]
"**/__init__.py" = [
    "D104", # ファイルの説明を不要にする
]
"src/usecases/**/*.py" = [
    "D100", # ユースケースには1関数しか配置しないため、モジュールのドキュメントが不要
]

[tool.ruff.lint.flake8-bugbear]
# FastAPIプロジェクトにおけるB008ルールの代替
# https://github.com/fastapi/fastapi/issues/1522#issuecomment-1435803420
extend-immutable-calls = ["fastapi.Depends", "fastapi.params.Depends", "fastapi.Query", "fastapi.params.Query"]

[tool.ruff.lint.isort]
combine-as-imports = true
force-sort-within-sections = true

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.format]
# https://docs.astral.sh/ruff/formatter/
docstring-code-format = true
indent-style = "space"
line-ending = "auto"


[tool.pyright]
typeCheckingMode = "strict"
# exclude = [
#     "**/migrations"
# ]